version: "3.8"

volumes:
  postgres:

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${USERNAME:-root}
      POSTGRES_PASSWORD: ${PASSWORD:-1}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ:-Asia/Tehran}
    ports:
      - "${PORT:-5432}:5432"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PGADMIN_PORT:-7100}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin